In [23]:
import pandas as pd 
from sklearn.decomposition import PCA 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
import seaborn as sn
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn import tree
from sklearn.ensemble import AdaBoostClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import numpy as np
from sklearn.metrics import log_loss
from sklearn.model_selection import GridSearchCV

In [50]:
df_test = pd.read_csv(r'C:\Users\Mayank1\Downloads\574_cert_proj_dataset_v3.0 (1)\test.csv')

In [51]:
df_train = pd.read_csv(r'C:\Users\Mayank1\Downloads\574_cert_proj_dataset_v3.0 (1)\train.csv')

In [52]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594 entries, 0 to 593
Columns: 193 entries, id to texture64
dtypes: float64(192), int64(1)
memory usage: 895.8 KB


In [53]:
df_test.head()

id   margin1   margin2   margin3   margin4   margin5   margin6   margin7  \
0   4  0.019531  0.009766  0.078125  0.011719  0.003906  0.015625  0.005859   
1   7  0.007812  0.005859  0.064453  0.009766  0.003906  0.013672  0.007812   
2   9  0.000000  0.000000  0.001953  0.021484  0.041016  0.000000  0.023438   
3  12  0.000000  0.000000  0.009766  0.011719  0.017578  0.000000  0.003906   
4  13  0.001953  0.000000  0.015625  0.009766  0.039062  0.000000  0.009766   

   margin8   margin9  ...  texture55  texture56  texture57  texture58  \
0      0.0  0.005859  ...   0.006836   0.000000   0.015625   0.000977   
1      0.0  0.033203  ...   0.000000   0.000000   0.006836   0.001953   
2      0.0  0.011719  ...   0.128910   0.000000   0.000977   0.000000   
3      0.0  0.003906  ...   0.012695   0.015625   0.002930   0.036133   
4      0.0  0.005859  ...   0.000000   0.042969   0.016602   0.010742   

   texture59  texture60  texture61  texture62  texture63  texture64  
0   0.015625        0.0        0.0   0.000000   0.003906   0.053711  
1   0.013672        0.0        0.0   0.000977   0.037109   0.044922  
2   0.000000        0.0        0.0   0.015625   0.000000   0.000000  
3   0.013672        0.0        0.0   0.089844   0.000000   0.008789  
4   0.041016        0.0        0.0   0.007812   0.009766   0.007812  

[5 rows x 193 columns]

In [54]:
df_test['id']

0         4
1         7
2         9
3        12
4        13
       ... 
589    1576
590    1577
591    1579
592    1580
593    1583
Name: id, Length: 594, dtype: int64

In [55]:
list =df_test.columns

In [56]:
list.all

<bound method Index._add_logical_methods.<locals>._make_logical_function.<locals>.logical_func of Index(['id', 'margin1', 'margin2', 'margin3', 'margin4', 'margin5', 'margin6',
       'margin7', 'margin8', 'margin9',
       ...
       'texture55', 'texture56', 'texture57', 'texture58', 'texture59',
       'texture60', 'texture61', 'texture62', 'texture63', 'texture64'],
      dtype='object', length=193)>

In [57]:
df_test.shape

(594, 193)

In [58]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 990 entries, 0 to 989
Columns: 194 entries, id to texture64
dtypes: float64(192), int64(1), object(1)
memory usage: 1.5+ MB


In [59]:
df_train['id']

0         1
1         2
2         3
3         5
4         6
       ... 
985    1575
986    1578
987    1581
988    1582
989    1584
Name: id, Length: 990, dtype: int64

In [60]:
df_train.head()

id                species   margin1   margin2   margin3   margin4  \
0   1            Acer_Opalus  0.007812  0.023438  0.023438  0.003906   
1   2  Pterocarya_Stenoptera  0.005859  0.000000  0.031250  0.015625   
2   3   Quercus_Hartwissiana  0.005859  0.009766  0.019531  0.007812   
3   5        Tilia_Tomentosa  0.000000  0.003906  0.023438  0.005859   
4   6     Quercus_Variabilis  0.005859  0.003906  0.048828  0.009766   

    margin5   margin6   margin7  margin8  ...  texture55  texture56  \
0  0.011719  0.009766  0.027344      0.0  ...   0.007812   0.000000   
1  0.025391  0.001953  0.019531      0.0  ...   0.000977   0.000000   
2  0.003906  0.005859  0.068359      0.0  ...   0.154300   0.000000   
3  0.021484  0.019531  0.023438      0.0  ...   0.000000   0.000977   
4  0.013672  0.015625  0.005859      0.0  ...   0.096680   0.000000   

   texture57  texture58  texture59  texture60  texture61  texture62  \
0   0.002930   0.002930   0.035156        0.0        0.0   0.004883   
1   0.000000   0.000977   0.023438        0.0        0.0   0.000977   
2   0.005859   0.000977   0.007812        0.0        0.0   0.000000   
3   0.000000   0.000000   0.020508        0.0        0.0   0.017578   
4   0.021484   0.000000   0.000000        0.0        0.0   0.000000   

   texture63  texture64  
0   0.000000   0.025391  
1   0.039062   0.022461  
2   0.020508   0.002930  
3   0.000000   0.047852  
4   0.000000   0.031250  

[5 rows x 194 columns]

In [61]:
df_train.shape

(990, 194)

In [62]:
df_train['species'].value_counts()

Lithocarpus_Cleistocarpus    10
Quercus_Ilex                 10
Alnus_Sieboldiana            10
Morus_Nigra                  10
Cytisus_Battandieri          10
                             ..
Tilia_Tomentosa              10
Tilia_Oliveri                10
Acer_Capillipes              10
Alnus_Maximowiczii           10
Quercus_Phellos              10
Name: species, Length: 99, dtype: int64

In [63]:
le = LabelEncoder()

In [64]:
## ENCODING THE LABEL COLUMN
df_train['species'] =le.fit_transform(df_train['species'])

In [65]:
df_train['species'].value_counts()

98    10
24    10
26    10
27    10
28    10
      ..
68    10
69    10
70    10
71    10
0     10
Name: species, Length: 99, dtype: int64

In [66]:
df_train['species'].describe()

count    990.000000
mean      49.000000
std       28.591824
min        0.000000
25%       24.000000
50%       49.000000
75%       74.000000
max       98.000000
Name: species, dtype: float64

In [67]:
X = df_train.iloc[:,2:].values
Y = df_train['species']
X.shape

(990, 192)

In [68]:
X_train, X_test, Y_train,Y_test = train_test_split(X,Y,test_size = .20, random_state = 1)

In [69]:
model = svm.SVC(kernel='linear')
model.fit(X_train,Y_train)
#Predict Output
predicted= model.predict(X_test)
print("SVM accuray:",accuracy_score(Y_test, predicted))

SVM accuray: 0.015151515151515152


In [71]:
## PARAMETER TUNING FOR THE SVM ALGORITHM

param_grid = {'C': [0.1, 1, 10, 100, 1000],  
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 
              'kernel': ['rbf']}  
  
grid = GridSearchCV(svm.SVC(), param_grid, refit = True, verbose = 3) 
  
# fitting the model for grid search 
grid.fit(X_train, Y_train) 

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................


C:\Users\Mayank1\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:667: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.107, total=   0.3s
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s


[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.113, total=   0.3s
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.6s remaining:    0.0s


[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.127, total=   0.3s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.120, total=   0.3s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.108, total=   0.3s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.107, total=   0.3s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.113, total=   0.3s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.127, total=   0.3s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.120, total=   0.3s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] .

[CV] ........ C=10, gamma=0.01, kernel=rbf, score=0.107, total=   0.3s
[CV] C=10, gamma=0.01, kernel=rbf ....................................
[CV] ........ C=10, gamma=0.01, kernel=rbf, score=0.113, total=   0.3s
[CV] C=10, gamma=0.01, kernel=rbf ....................................
[CV] ........ C=10, gamma=0.01, kernel=rbf, score=0.127, total=   0.3s
[CV] C=10, gamma=0.01, kernel=rbf ....................................
[CV] ........ C=10, gamma=0.01, kernel=rbf, score=0.120, total=   0.3s
[CV] C=10, gamma=0.01, kernel=rbf ....................................
[CV] ........ C=10, gamma=0.01, kernel=rbf, score=0.108, total=   0.3s
[CV] C=10, gamma=0.001, kernel=rbf ...................................
[CV] ....... C=10, gamma=0.001, kernel=rbf, score=0.107, total=   0.3s
[CV] C=10, gamma=0.001, kernel=rbf ...................................
[CV] ....... C=10, gamma=0.001, kernel=rbf, score=0.113, total=   0.3s
[CV] C=10, gamma=0.001, kernel=rbf ...................................
[CV] .

[CV] ..... C=1000, gamma=0.001, kernel=rbf, score=0.215, total=   0.3s
[CV] C=1000, gamma=0.001, kernel=rbf .................................
[CV] ..... C=1000, gamma=0.001, kernel=rbf, score=0.203, total=   0.4s
[CV] C=1000, gamma=0.0001, kernel=rbf ................................
[CV] .... C=1000, gamma=0.0001, kernel=rbf, score=0.107, total=   0.3s
[CV] C=1000, gamma=0.0001, kernel=rbf ................................
[CV] .... C=1000, gamma=0.0001, kernel=rbf, score=0.113, total=   0.3s
[CV] C=1000, gamma=0.0001, kernel=rbf ................................
[CV] .... C=1000, gamma=0.0001, kernel=rbf, score=0.127, total=   0.3s
[CV] C=1000, gamma=0.0001, kernel=rbf ................................
[CV] .... C=1000, gamma=0.0001, kernel=rbf, score=0.120, total=   0.3s
[CV] C=1000, gamma=0.0001, kernel=rbf ................................
[CV] .... C=1000, gamma=0.0001, kernel=rbf, score=0.108, total=   0.3s


[Parallel(n_jobs=1)]: Done 125 out of 125 | elapsed:   36.7s finished


GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [72]:
model = svm.SVC(C=1000, gamma=0.1, kernel='rbf')
model.fit(X_train,Y_train)
#Predict Output
predicted= model.predict(X_test)
print("SVM accuray:",accuracy_score(Y_test, predicted))
## PARAMETER TUNING GIVES THE CORRECT PARAMETERS FOR THE MODEL 

SVM accuray: 0.9444444444444444


In [73]:
predicted

array([90, 47,  2,  3,  6, 81, 64, 75, 71, 26, 30, 54, 85, 24, 93, 49, 89,
       46, 49, 32, 20, 18, 92, 21, 11, 63, 72, 62, 50,  5, 59, 55, 86, 43,
       54, 73, 42, 54,  0, 93,  2, 34, 65, 48, 31, 32, 12,  3, 28, 15, 83,
       13, 95, 69,  5, 41, 27, 68, 41, 45, 70, 66, 23, 63,  0,  4, 53, 48,
        9, 89, 21, 82, 33, 23, 21, 37,  3, 20, 65, 96, 82, 15, 12, 98, 54,
       61, 64, 33,  4, 83, 12, 28, 14, 94, 54, 34, 62, 50, 26,  1, 19, 96,
       19, 33, 78,  9, 22, 79, 40, 20, 86, 88, 95, 95, 18, 22, 61,  6, 94,
       46, 16, 77, 20, 87, 90, 60, 78,  7, 23, 93, 33, 65, 92, 39, 20, 41,
       84,  9, 60, 36, 66, 86,  0, 74, 95, 26, 11, 22, 17, 11, 53,  0, 58,
       13, 10, 46,  8, 53, 42, 87, 28, 77, 56, 14, 45, 98, 61, 44, 18, 96,
       91, 89, 70, 54, 25, 76, 97, 26, 94, 37, 61, 59, 59, 65, 39, 13,  4,
       97, 16, 46, 40, 63, 47, 22, 71, 39, 45,  6])

In [74]:
cnf_matrix_svm = confusion_matrix(Y_test,predicted )
print(cnf_matrix_svm)

[[4 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 ...
 [0 0 0 ... 3 0 0]
 [0 0 0 ... 0 2 0]
 [0 0 0 ... 0 0 2]]


In [75]:
## FITTING GAUSSIAN NB ON THE TRAIN DATASET

In [76]:
gnb = GaussianNB()
gnb.fit(X_train,Y_train )
target_pred =gnb.predict(X_test)

In [77]:
print('Accuracy:',abs(metrics.accuracy_score(Y_test,target_pred)))

Accuracy: 0.47474747474747475


In [78]:
cnf_matrix_gnb = confusion_matrix(Y_test,target_pred )
print(cnf_matrix_gnb)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 2]]


In [79]:
## FITTING RANDOM FOREST CLASSIFIER ON THE TRAIN DATASET

In [80]:
rf = RandomForestClassifier()
rf.fit(X_train,Y_train)
Y_pred = rf.predict(X_test)
print('Accuracy:',abs(metrics.accuracy_score(Y_test,Y_pred)))
## ********RANDOM FOREST IS THE MOST ROBUST MODEL *********

Accuracy: 0.9595959595959596


In [81]:
cnf_matrix_rf = confusion_matrix(Y_test,Y_pred )
print(cnf_matrix_rf)

[[4 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 ...
 [0 0 0 ... 3 0 0]
 [0 0 0 ... 0 2 0]
 [0 0 0 ... 0 0 2]]


In [82]:
## FITTING DECISION TREE ON THE TRAIN DATASET

In [83]:
dt = tree.DecisionTreeClassifier()
dt.fit(X_train,Y_train)
Y_pred = dt.predict(X_test)

In [84]:
print('Accuracy:',abs(metrics.accuracy_score(Y_test,Y_pred)))

Accuracy: 0.5959595959595959


In [85]:
## PARAMETER TUNING FOR THE DESCISION TREE

from sklearn.model_selection import GridSearchCV

max_depth =[3, None]
max_features = [1,2,3,4,5,6,7,8,9]
min_samples_leaf = [1,2,3,4,5,6,7,8,9]
criterion = ["gini", "entropy"]


param_dist = {"max_depth": max_depth,
              "max_features": max_features,
              "min_samples_leaf": min_samples_leaf,
              "criterion": criterion}

dt = tree.DecisionTreeClassifier()


dt_tune = GridSearchCV(estimator = dt, param_grid = param_dist, cv = 2, verbose=2, n_jobs = -1)
dt_tune.fit(X_train, Y_train)

print(dt_tune.best_params_)

Fitting 2 folds for each of 324 candidates, totalling 648 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:    4.6s


{'criterion': 'gini', 'max_depth': None, 'max_features': 7, 'min_samples_leaf': 1}


[Parallel(n_jobs=-1)]: Done 648 out of 648 | elapsed:    7.5s finished


In [86]:
dt = tree.DecisionTreeClassifier(criterion= 'gini', max_depth= None, max_features = 8, min_samples_leaf =1)
dt.fit(X_train,Y_train)
Y_pred = dt.predict(X_test)

In [87]:
print('Accuracy:',abs(metrics.accuracy_score(Y_test,Y_pred)))

Accuracy: 0.5606060606060606


### NOW WE TEST THE SAME MODELS AGAINST THE TEST DATASET

In [88]:
test_data = df_test.iloc[:,1:].values
## REMOVING THE ID COLUMN FROM TEST DATASET

In [90]:
#Predict Output throug the SVm model built before
predicted= model.predict(test_data)
print(predicted)

[51 50  1 19 14  3  3 28 84  8 43 74 75 10 52 60 45 73 13 71 61 68 57 77
  1 70 28 15 35 70 53 74 47 50  4 36 14 55 36 93  8 32  8  9 71 70 38 23
 94 18 13  5 55 94 14 86 62 33 51 98 88 56 21 59 65 11 48  5 13  4 54 57
 29  7 31 98 92 84 25 10 61 43 85 24  1  2 23 83 40 22 48 90 25 21 37 56
 41 95  7 89 98 77  3 12 31 84 53 96 64 72 93 93 67 30  8 88 60 87  6 57
 34 90 60 17 75 27 51  7 39 23 96  2 41 61 24 97 29 28 68 81 42 51 86 62
 60 52 95 81 42 96 95 20 59 35 86  1 26 38 43 75 20 60 46 79 22 79 69 87
 65 97 75 21 29 21 11 10 58 94 27 22 15 45 89 54 43  5 23 94 40 49 89 72
 36 11 64 95 18 91 29 64 80  6 78 45 28  9 78 90 44 89 92 13  2 59  0 96
 70 32 29 78 91 69 44 38  5 60 49 58 94 67  7 88 90 79 25 37 18  0 76 27
 70 71 44 70 32 90 30 82 34 30 82 96 48 65 57 64 26 53 55 73  9 86 83 26
 30 63 17 22 36 63 12 78 36 14 27 25 67 38 20 54 76 69 67 97 80 44 92 69
 23 21 94 51 33 77 16 11 97  1 52 39 24 52 42 52  2 73 96 83 88  9 63 50
 16 38 87 95  3 35 83 60 59 58  0 50 62 38 93 68 69

In [91]:
#Predict Output throug the gnb model built before
target_pred =gnb.predict(test_data)
target_pred

array([51, 50,  1, 19, 14,  3, 50, 69, 19, 19, 43, 85, 75, 10, 52, 26, 69,
       26, 14, 71, 68, 69, 57, 77,  1, 47, 79, 15, 35, 70, 53, 16, 47, 50,
        4, 87, 14, 50, 36, 93, 19, 19, 19,  9, 71, 70, 38, 70, 41, 69, 86,
       19, 55, 94, 12, 50, 62, 69, 51, 98, 83, 51, 46, 59, 47, 11, 47, 74,
       13,  4, 85, 57, 29,  7, 31, 85, 73, 85, 36, 10, 55, 47, 85, 24, 85,
        2, 23, 83, 87, 36, 85, 69, 70, 83, 70, 56, 41, 17,  7, 48, 85, 77,
        3, 12, 31, 10, 12, 96, 64, 70, 93, 14, 67, 45, 16, 19, 60, 87,  6,
       44, 34, 90, 60, 14, 75, 27, 51, 73, 39, 23, 55,  2, 41, 68, 24, 14,
       28, 28,  3, 81, 42, 51, 50, 52, 60, 52, 14, 64, 42, 93, 14, 20, 59,
       35, 86,  1, 26, 38, 96, 83, 85, 60, 12, 79, 26, 79, 50, 87, 65, 77,
       51, 21, 79, 87, 11, 10, 58, 94, 27, 19, 15, 45, 73, 85, 47, 80, 24,
       94, 40, 49, 73, 70, 36, 93, 81, 95, 74, 91, 29, 64, 80, 47, 78, 45,
       85,  9, 78, 85, 44, 73, 92, 47,  2, 78, 85, 96, 70, 32, 79, 78, 91,
       69, 44, 34,  5, 79

In [92]:
#Predict Output throug the rf model built before
Y_pred = rf.predict(test_data)
Y_pred

array([51, 50,  1, 19, 14,  3,  3, 29, 84,  8, 43, 74, 75, 10, 52, 46, 45,
       73, 13, 71, 61, 68, 57, 77,  1, 70, 28, 15, 35, 70, 53, 74, 47, 50,
        4, 36, 14, 55, 36, 93,  8, 32,  8,  9, 71, 70, 38, 23, 94, 18, 17,
        5, 55, 94, 14, 86, 62, 33, 51, 98, 88, 56, 21, 59, 65, 11, 48,  5,
       13,  4, 54, 57, 29,  7, 31, 98, 92, 84, 25, 10, 61, 43, 85, 24,  1,
        2, 24, 83, 40, 22, 48, 90, 25, 21, 37, 56, 41, 95,  7, 89, 98, 77,
        3, 12, 31, 84, 53, 96, 64, 72, 93, 93, 67, 30,  8, 88, 60, 87,  6,
       57, 34, 90, 60, 17, 75, 27, 51, 31, 39, 23, 24,  2, 41, 61, 24, 97,
       29, 28, 68, 81, 42, 51, 86, 62, 60, 52, 95, 93, 42, 34, 95, 20, 59,
       35, 86,  1, 26, 38, 43, 75, 20, 60, 46, 81, 22, 79, 55, 87, 10, 97,
       75, 21, 29, 21, 11, 10, 58, 94, 27, 22, 15, 45, 89, 54, 43,  5, 23,
       94, 40, 49, 89, 72, 36, 11, 81, 95, 18, 91, 29, 64, 80,  6, 78, 45,
       28,  9, 78, 90, 44, 89,  7, 13,  2, 59,  0, 96, 70, 32, 29, 78, 91,
       55, 44, 38,  5, 60